apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio
  namespace: minio
  labels:
    app: minio
    env: k3s
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
