apiVersion: v1
kind: ServiceAccount
metadata:
  name: logicalis-report-health-check
  namespace: logicalis
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: logicalis-report-health-check
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "persistentvolumeclaims", "persistentvolumes", "events", "secrets", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes", "pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["config.openshift.io"]
  resources: ["clusteroperators"]
  verbs: ["get", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: logicalis-report-health-check-binding
subjects:
- kind: ServiceAccount
  name: logicalis-report-health-check
  namespace: logicalis
roleRef:
  kind: ClusterRole
  name: logicalis-report-health-check
  apiGroup: rbac.authorization.k8s.io