apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug-upgrade-oc
  namespace: debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debug-upgrade-oc
rules:
- apiGroups: ["apiserver.openshift.io"]
  resources: ["apirequestcounts"]
  verbs: ["get", "list"]
- apiGroups: [""]
  resources: ["configmaps"]
  verbs: ["get", "patch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debug-upgrade-oc-binding
subjects:
- kind: ServiceAccount
  name: debug-upgrade-oc
  namespace: debug
roleRef:
  kind: ClusterRole
  name: debug-upgrade-oc
  apiGroup: rbac.authorization.k8s.io