services:
  alpine:
    image: alpine
    container_name: alpine
    build:
      context: '.'
      dockerfile: ./Docker/dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMAGE_ALPINE: "alpine:latest"
    restart: always
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: example
    #   MONGO_INITDB_DATABASE: restaurant
    # volumes:
    #   - mongo_data:/data/db
    #   - ./Docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    # ports:
    #   - 27017:27017
volumes:
  mongo_data: {}
