apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug-report-health-check
  namespace: debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debug-report-health-check
rules:
- apiGroups: [""]
  resources: ["pods", "nodes", "persistentvolumeclaims", "persistentvolumes", "events", "secrets", "namespaces"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["nodes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debug-report-health-check-binding
subjects:
- kind: ServiceAccount
  name: debug-report-health-check
  namespace: debug
roleRef:
  kind: ClusterRole
  name: debug-report-health-check
  apiGroup: rbac.authorization.k8s.io