apiVersion: v1
kind: Pod
metadata:
  name: debug
  namespace: debug
spec:
  containers:
    - name: debug
      image: portainer/kube-tools:latest
      #command: ["/bin/bash", "-c", "sh /scripts/oneliner.sh"]
      command:
        - /bin/bash
        - -c
        - |
          bash /utils/system.bash
          bash /utils/alias.bash
          bash /utils/oc.bash
          while true; do sleep 30; done
      volumeMounts:
        - name: utils
          mountPath: /utils
        - name: reports
          mountPath: /reports
        - name: writable-volume
          mountPath: /debug
      resources:
        requests:
          memory: "256Mi"
          cpu: "500m"
        limits:
          memory: "1024Mi"
          cpu: "1000m"
  serviceAccountName: debug
  volumes:
    - name: utils
      configMap:
        name: debug-configmap
    - name: reports
      configMap:
        name: health-check-scripts
    - name: writable-volume
      emptyDir: {}
  restartPolicy: Never
