apiVersion: v1
kind: ServiceAccount
metadata:
  name: debug
  namespace: debug
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: debug-operator
subjects:
  - kind: ServiceAccount
    name: debug
    namespace: debug
  - kind: Group
    name: debug-users
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: debug-operator-resource
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: debug-operator-resource
rules:
  - apiGroups: [""]
    resources: ["pods", "nodes", "persistentvolumeclaims", "persistentvolumes", "events", "secrets", "namespaces"]
    verbs: ["get", "list", "watch"]
  - apiGroups: [""]
    resources: ["events"]
    verbs: ["get", "list", "watch", "delete"]
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["metrics.k8s.io"]
    resources: ["nodes", "pods"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["config.openshift.io"]
    resources: ["clusteroperators"]
    verbs: ["get", "list"]
  - apiGroups: ["coordination.k8s.io"]
    resources: ["leases"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["cert-manager.io"]
    resources: ["issuers", "clusterissuers", "certificates"]
    verbs: ["get", "list", "watch"]
  - apiGroups: ["apiserver.openshift.io"]
    resources: ["apirequestcounts"]
    verbs: ["get", "list"]
  - apiGroups: [""]
    resources: ["configmaps"]
    verbs: ["get", "patch"]