version: '3.7'
services:
  nexus:
    container_name: nexus
    image: sonatype/nexus3:3.56.0
    ports:
      - "8081:8081"
      - "8082:8082"
      - "8083:8083"
      - "8084:8084"
    environment:
      INSTALL4J_ADD_VM_PARAMS: "-Xms4G -Xmx4G -XX:MaxDirectMemorySize=6717m -Djava.util.prefs.userRoot=/nexus-data/javaprefs"
    volumes:
      - /var/lib/docker/volumes/nexus/nexus-data:/nexus-data
