services:
  mongodb:
    image: mongo
    container_name: mongodb
    build:
      context: '.'
      dockerfile: ./Docker/dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMAGE_OPENSUSELEAP: "opensuse/leap:latest"
    restart: always
    volumes:
      - mongo_data:/data/db
      - ./Docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 27017:27017
volumes:
  mongo_data: {}
