apiVersion: batch/v1
kind: CronJob
metadata:
  name: health-check-cronjob
  namespace: debug
spec:
  schedule: "*/5 * * * *"
  #schedule: "1 6 * * 1-5"
  successfulJobsHistoryLimit: 5
  failedJobsHistoryLimit: 5
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      activeDeadlineSeconds: 435600
      backoffLimit: 0
      template:
        spec:
          containers:
          - name: health-check
            image: portainer/kube-tools:latest
            imagePullPolicy: Always
            command:
              - /bin/bash
              - -c
              - |
                export parameter_yq_version="v4.44.3"
                export parameter_oc_client_pre="https://downloads-openshift-console.apps.gmaopro.northeurope.aroapp.io/amd64/linux/oc.tar"
                export parameter_oc_client_pro="https://downloads-openshift-console.apps.gmao.northeurope.aroapp.io/amd64/linux/oc.tar"
                export parameter_events_ignore_string="Readiness|Liveness|timeout|healthz|crunchy"
                export parameter_certificates_evade_subjects="system:kube-controller-manager system:kube-scheduler system:openshift-aggregator system:serviceaccount:openshift-kube-apiserver:check-endpoints system:masters api.gmaopro.northeurope.aroapp.io api.gmao.northeurope.aroapp.io api-int.gmaopro.northeurope.aroapp.io api-int.gmao.northeurope.aroapp.io kube-master 127.0.0.1 172.30.0.1 openshift-kube-apiserver-operator_aggregator-client-signer@ kube-csr-signer_ system:serviceaccount:openshift-monitoring:prometheus-k8s system:serviceaccount:openshift-oauth-apiserver:openshift-authenticator 'Red Hat, Inc.'"
                sh /scripts/oneliner.sh "$parameter_yq_version" "$parameter_oc_client_pre" "$parameter_oc_client_pro" "$parameter_events_ignore_string" "$parameter_certificates_evade_subjects"
            volumeMounts:
            - name: scripts
              mountPath: /scripts
            - name: writable-volume
              mountPath: /tmp
            resources:
              requests:
                memory: "256Mi"
                cpu: "200m"
              limits:
                memory: "512Mi"
                cpu: "500m"
          serviceAccountName: debug-report-health-check 
          restartPolicy: Never
          volumes:
          - name: scripts
            configMap:
              name: health-check-scripts
          - name: writable-volume
            emptyDir: {}