services:
  mysql5:
    container_name: mysql5
    build:
      context: '.'
      dockerfile: ./Docker/dockerfile
      args:
        DOCKER_REGISTRY_CACHE: "docker.io"
        IMAGE_MYSQL5: "mysql:5.7.43"
    # volumes:
    #   - db_data:/var/lib/mysql
    #   - ./Docker/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "4036:3306"
    restart: always
    environment:
      ENVIRONMENT: DEV
      MYSQL_ROOT_PASSWORD: 1nternet!
      MYSQL_DATABASE: sistemes
      MYSQL_USER: sistemes
      MYSQL_PASSWORD: 1nternet!
networks:
  apps:
    name: mysql5
volumes:
  db_data: {}
