kind: CronJob
apiVersion: batch/v1
metadata:
  name: maximo-backup-db2u-integracion-v1
  namespace: db2u
spec:
  schedule: 0 1 * * *
  concurrencyPolicy: Forbid
  suspend: false
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      activeDeadlineSeconds: 600
      backoffLimit: 1
      template:
        metadata:
          creationTimestamp: null
        spec:
          containers:
            - name: db2u-backup
              image: 'registry.redhat.io/openshift4/ose-cli:v4.12'
              command:
                - /bin/bash
                - '-c'
                - 'TODAY=$(date +"%Y%m%d"); OBJ_NAME="$CR_NAME-$TODAY"; echo "$DB2U_BACKUP_TEMPLATE" | sed -e "s/{\$CR_NAME}/$OBJ_NAME/ | sed -e "s/{\$NAMESPACE}/$NAMESPACE/" | sed -e "s/{\$DB2UNAME}/$DB2U_DB_NAME/" | sed  -e "s/{\$DB2UZONE}/$DB2U_DB_ZONE/"> /tmp/db2ubackup.yaml; oc create -n $NAMESPACE -f /tmp/db2ubackup.yaml'
              env:
                - ame: CR_NAME
                  value: db2u-backup-integracion
                - name: NAMESPACE
                  value: db2u
                - name: DB2U_DB_NAME
                  value: BLUBD
                - name: DB2U_DB_ZONE
                  value: maxdbpre
                - name: DB2U_BACKUP_TEMPLATE
                  valueFrom:
                    configMapKeyRef:
                      name: backup-db2u-crd-template
                      key: TEMPLATE
              resources: {}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              imagePullPolicy: IfNotPresent
          restartPolicy: Never
          terminationGracePeriodSeconds: 30
          dnsPolicy: ClusterFirst
          serviceAccountName: maximo-backup-db2u
          serviceAccount: maximo-backup-db2u
          securityContext: {}
          schedulerName: default-scheduler
  successfulJobsHistoryLimit: 1
  failedJobsHistoryLimit: 1